### PR TITLE
refactor and fix some issues

### LINKED ISSUE #77: Trying to access array offset on value of type null in the browser.
**Describe the bug**
Trying to access array offset on value of type null in the browser.

**To Reproduce**
1. Run the docker-compose up -d
2. Install composer
3. Go to the server name in a browser
4. See the error

**Expected behavior**
I want when going to the site in the browser, this error will not appear

**Screenshots**
image

**Desktop:**
 - OS: Linux - Ubuntu
 - Browser: Chrome
 - Version 114.0.5735.198 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by tanhongit**

### CODE REVIEW

File: src/Services/TelegramService.php [hunk 1]
```diff
@@ -74,7 +74,7 @@ private function sendCallbackResponse(string $callback = null): void
      */
     public function checkCallback(): bool
     {
-        if (!is_null($this->telegram->Callback_ChatID())) {
+        if (!is_null($this->telegram->getData()) && !is_null($this->telegram->Callback_ChatID())) {
```
Comment (tanhongit) [inline src/Services/TelegramService.php:77]: fix to access array offset on the value of type null
