### PR TITLE
fix: update conditions to access denied channel before send notify

### LINKED ISSUE #42: Check access denied channel before send notify

### PR DESCRIPTION
**Pull request by tanhongit**

### CODE REVIEW

File: src/Services/NotificationService.php [hunk 1]
```diff
@@ -86,13 +86,18 @@ public function sendNotify(string $chatId, string $message = null): bool
         $url = $method_url . '?chat_id=' . $chatId . '&disable_web_page_preview=1&parse_mode=html&text='
             . urlencoded_message($this->message);
 
-        $client = new Client();
-        $response = $client->request('GET', $url);
+        try {
```
Comment (tanhongit) [inline src/Services/NotificationService.php:91]: To fix this issue (#42)
